### ISSUE TITLE
Кривой канвас

### ISSUE THREAD

**Issue by Red-Cat-Fat** [maxPow1776/houseAttack#1]
![image](https://user-images.githubusercontent.com/28541280/81596863-6e84d800-93cd-11ea-8d72-5a6c039020e3.png)
Проверяй на разных разрешениях экрана, а не только на своём

**Comment by maxPow1776** [comment]
Исправил https://github.com/maxPow1776/houseAttack/commit/5cf4c3e5f41277aa3bd102850819eedd160232da
