### ISSUE TITLE
Не стоит комментровать неиспользуемый код

### ISSUE THREAD

**Issue by Red-Cat-Fat** [maxPow1776/houseAttack#10]
https://github.com/maxPow1776/houseAttack/blob/f45c8437c87eb2b51fc3f4feb14f51820c4ac43c/Assets/Scripts/Multiplayer/PlayerControllerMultiplayer.cs#L31-L39

**Comment by maxPow1776** [comment]
Исправил https://github.com/maxPow1776/houseAttack/commit/e8236fd2011baf6d3f033bed99816679dff12563
