### ISSUE TITLE
Зачем тебе 2 компонента да и ещё с такими названиями?

### ISSUE THREAD

**Issue by Red-Cat-Fat** [maxPow1776/houseAttack#3]
Зачем ты создал 2 одинаковых компонента, отличающихся только именами?
![image](https://user-images.githubusercontent.com/28541280/81597363-4d70b700-93ce-11ea-866b-851e5c2a0ff5.png)
![image](https://user-images.githubusercontent.com/28541280/81597387-55305b80-93ce-11ea-973a-a5b5d467a5d1.png)

**Comment by Red-Cat-Fat** [comment]
То же самое касается и классов ShootButton и BombButton в папке UI. Да и вообще зачем разделять логиккопипастить локигу под Bomb и Shoot?

**Comment by maxPow1776** [comment]
Исправил https://github.com/maxPow1776/houseAttack/commit/731d854c50a90c8a21c1e23e38fa50abe6b8fee7
