### ISSUE TITLE
Не используй рефлексию

### ISSUE THREAD

**Issue by Red-Cat-Fat** [maxPow1776/houseAttack#5]
![image](https://user-images.githubusercontent.com/28541280/81597788-f28b8f80-93ce-11ea-9c39-626840a6d000.png)
В данном случае ты мог бы использовать корутину и тогда всё нормально бы работало.

**Comment by maxPow1776** [comment]
Исправил https://github.com/maxPow1776/houseAttack/commit/7fcf7218a02671c1ea990461df4dd3d1d2e3cb29

**Comment by Red-Cat-Fat** [comment]
Зачем комментировать куски кода? У тебя есть гит, чтобы вернуться на версию раньше. Так что удаляй закомментированные куски кода.
