### ISSUE TITLE
Не хардкодь!

### ISSUE THREAD

**Issue by Red-Cat-Fat** [maxPow1776/houseAttack#6]
![image](https://user-images.githubusercontent.com/28541280/81597947-2ff01d00-93cf-11ea-9b5c-fbd9045a933c.png)
Почему 4? Почему не 5? Не стоить хардкодить значения

**Comment by maxPow1776** [comment]
Исправил https://github.com/maxPow1776/houseAttack/commit/ecfaf3dc670ac16e5c938eef19f8a211f43af7d4
