### ISSUE TITLE
Вычисляй расстояние с помощью стандартных библиотек

### ISSUE THREAD

**Issue by Red-Cat-Fat** [maxPow1776/houseAttack#8]
Управление анимациями в целом логичное, но вычислять расстояние можено через [Vector3.Distance()](https://docs.unity3d.com/ScriptReference/Vector3.Distance.html)
https://github.com/maxPow1776/houseAttack/blob/f45c8437c87eb2b51fc3f4feb14f51820c4ac43c/Assets/Scripts/Controllers/AnimatoinsController.cs#L22

**Comment by maxPow1776** [comment]
Поправил https://github.com/maxPow1776/houseAttack/commit/9597c6219f51a6d689bf790447a9289a17eba0f9
