### ISSUE TITLE
NRE

### ISSUE THREAD

**Issue by Red-Cat-Fat** [maxPow1776/houseAttack#9]
https://github.com/maxPow1776/houseAttack/blob/f45c8437c87eb2b51fc3f4feb14f51820c4ac43c/Assets/Scripts/Controllers/EnemyController.cs#L19

**Comment by Red-Cat-Fat** [comment]
Ещё 
https://github.com/maxPow1776/houseAttack/blob/f45c8437c87eb2b51fc3f4feb14f51820c4ac43c/Assets/Scripts/Multiplayer/LookAt.cs#L12-L13

**Comment by maxPow1776** [comment]
Исправил https://github.com/maxPow1776/houseAttack/commit/71c69c2f107a81e467464a24133ff7371f4b34c4
